-- 墨读·小说引力场 增量迁移脚本（PostgreSQL）
-- 适用：已有旧库（app_novel_book 等 9 表已存在）的增量升级，幂等可重复执行
-- 说明：勿整份执行 app_pgsql.sql（含 DROP TABLE，会清空数据）

-- 1. 读者扩展资料：禁言字段（2026-08-07 新增）
ALTER TABLE "public"."app_novel_reader_profile" ADD COLUMN IF NOT EXISTS "ban_post_until" timestamptz(0);
ALTER TABLE "public"."app_novel_reader_profile" ADD COLUMN IF NOT EXISTS "ban_reason" varchar(255) NOT NULL DEFAULT '';

-- 2. 意见反馈/投诉表
CREATE TABLE IF NOT EXISTS "public"."app_novel_feedback" (
  "id" BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "user_id" BIGINT NOT NULL,
  "user_name" varchar(64) NOT NULL DEFAULT '',
  "type" CHAR(1) NOT NULL,
  "kind" CHAR(16) NOT NULL DEFAULT 'feedback',
  "content" TEXT NOT NULL,
  "status" CHAR(1) NOT NULL DEFAULT '1',
  "created_at" timestamptz(0) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE "public"."app_novel_feedback" OWNER TO "postgres";
CREATE INDEX IF NOT EXISTS "idx_feedback_user" ON "public"."app_novel_feedback" USING btree ("user_id");
CREATE INDEX IF NOT EXISTS "idx_feedback_kind" ON "public"."app_novel_feedback" USING btree ("kind");

-- 3. 用户系统通知表
CREATE TABLE IF NOT EXISTS "public"."app_novel_notification" (
  "id" BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "user_id" BIGINT NOT NULL,
  "title" varchar(100) NOT NULL,
  "content" TEXT NOT NULL,
  "is_read" CHAR(1) NOT NULL DEFAULT '0',
  "source" CHAR(16) NOT NULL DEFAULT 'system',
  "notice_id" BIGINT,
  "created_at" timestamptz(0) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE "public"."app_novel_notification" OWNER TO "postgres";
CREATE INDEX IF NOT EXISTS "idx_notification_user" ON "public"."app_novel_notification" USING btree ("user_id");
CREATE INDEX IF NOT EXISTS "idx_notification_source" ON "public"."app_novel_notification" USING btree ("source", "notice_id");

-- 4. 后台系统公告表
CREATE TABLE IF NOT EXISTS "public"."app_novel_notice" (
  "id" BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "title" varchar(100) NOT NULL,
  "content" TEXT NOT NULL,
  "valid_days" INT NOT NULL DEFAULT 0,
  "create_by" BIGINT NOT NULL DEFAULT 0,
  "created_at" timestamptz(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz(0) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE "public"."app_novel_notice" OWNER TO "postgres";
-- 兼容：旧库若已有 app_novel_notice 且缺 valid_days 列（幂等）
ALTER TABLE "public"."app_novel_notice" ADD COLUMN IF NOT EXISTS "valid_days" INT NOT NULL DEFAULT 0;
